console.log("hello,world");
let a = 10;
let b = 20;
console.log(a + b);
 let  baskit1 = "mango";
 let  baskit2 = "apple";
 baskit1 = baskit2;
 console.log(baskit1);
 let ali = "7";
 let code = 7;
 console.log(ali === code);
 let score = 100;
 score =  score + 1;
 console.log(score);
 let age = 18;
 let  arman = 18;
 console.log(age >=  arman);
 let phone = 10;
 let phones = 12;
 console.log(phone <= phones);
